### ISSUE TITLE
feature/join-forms-to-api: get all agents returns insufficient data

### ISSUE THREAD

**Issue by LeosPrograms** [Carbon-Farm-Network/app-carbon-farm-network#10]
the data returned appears thus
[{__typename: "Organization"}]

**Comment by pospi** [comment]
Right you are! The latest commit should fix it.
The issue was my misunderstanding of how GraphQL processes fragments- because the one being used was for the interface type `Agent`, rather than the concrete `Organization` type, it wasn't being honoured and so nothing was returned. Now all the variants are mixed in and it GraphQL appears to be happily matching and returning what's been requested.

@fosterlynn just a note to add that this is an(other) issue caused by https://lab.allmende.io/valueflows/vf-schemas/vf-graphql/-/issues/101 and would cease to cause developer confusion if we re-abstracted agent. I think we might also need to hurry that issue along if the intention is to be creating `EcologicalAgents` with this app; since it's currently not possible in GraphQL (only people and organizations can be created).

**Comment by fosterlynn** [comment]
>@fosterlynn just a note to add that this is an(other) issue caused by https://lab.allmende.io/valueflows/vf-schemas/vf-graphql/-/issues/101 and would cease to cause developer confusion if we re-abstracted agent.

Replied in the vf-graphql space.
