### ISSUE TITLE
App freezes with map

### ISSUE THREAD

**Issue by textilelab** [Carbon-Farm-Network/app-carbon-farm-network#58]
We loaded multiple agents and when we tried to view on the map, only four icons showed up and the map made the system freeze. We could click on the menu items but nothing opened up.

**Comment by fosterlynn** [comment]
We "fixed" this by managing to intercept the app before the map came up, and going to the agent list.  Put in new long/lat in each agent, then the map comes up, and everything else works fine.

So, looks like some "bad" data was in the long/lat (we aren't validating that).  I'm leaving this as an open issue, because at some point, we'll need to add validations. And/or make the map not choke on bad data.  But for now, low priority, we can just be careful.
